- id: '1586806110083'
  alias: Bericht aan Marielle als Jasper van werk vertrekt
  description: ''
  trigger:
  - entity_id: device_tracker.gpslogger_pixel4a
    event: leave
    platform: zone
    zone: zone.contour_winterswijk
  - platform: zone
    entity_id: device_tracker.gpslogger_pixel4a
    zone: zone.anvil_valkenswaard
    event: leave
  - platform: zone
    entity_id: device_tracker.gpslogger_pixel4a
    zone: zone.rols_geldrop
    event: leave
  condition: []
  action:
  - service: notify.mobile_app_marielle_pixel_3a
    data:
      message: Jasper van werk vertrokken!
  mode: single
