- id: '1586290054304'
  alias: Thermostaat zolder uitzetten
  description: ''
  trigger:
  - at: '22:45:00'
    platform: time
  condition: []
  action:
  - data:
      hvac_mode: 'off'
      temperature: 14
    entity_id: climate.thermostaat_studeerzolder_climate
    service: climate.set_temperature
- id: '1586806110083'
  alias: Bericht aan marielle als Jasper van werk vertrekt
  description: ''
  trigger:
  - entity_id: device_tracker.jasper_app_galaxy_s7o
    event: leave
    platform: zone
    zone: zone.contour_winterswijk
  condition: []
  action:
  - data:
      message: Jasper is in Winterswijk vertrokkken
      title: Nu koken jij
    service: notify.mobile_app_marielle_app_xiaomi
