- alias: Waarschuw beweging bij afwezig
  description: ''
  trigger:
  - entity_id: binary_sensor.gang_sensor_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: device_tracker.jasper_galaxy_s7
    state: not_home
  - condition: state
    entity_id: device_tracker.iphonevmarielle
    state: not_home
  - condition: state
    entity_id: device_tracker.marielle_xiaomi
    state: not_home
  action:
  - data:
      message: Beweging in gang gedetecteerd
      title: Alarm
    service: notify.mobile_app_app_jasper_sm_g935f
