default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml

logger:
  default: info 
  logs:
    homeassistant.helpers.script: debug
    #homeassistant.components.history: debug
    #homeassistant.components.recorder: debug
    #homeassistant.components.unifi: debug

python_script:

http:
  server_port: !secret server_port 
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 5

google_assistant:
  project_id: !secret google_assistant_project_id 
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: false
  expose_by_default: true
  entity_config:
    script.skyradio_on:
      name: SKYRADIO
      aliases:
        - SKY RADIO
      expose: true
      room: Woonkamer

    script.esmee_disco_on:
      name: ESMEE DISCO
      aliases:
        - ESMEE DISCO
        - KINDERFEESTJE
      expose: true
      room: Woonkamer

    script.jokie_playlist_on:
      name: JOKIE
      aliases:
        - JOKIE
      expose: true
      room: Woonkamer

  exposed_domains:
    - light
    - scene

tts:
  - platform: google_translate

emulated_roku:
  servers:
    - name: Home Assistant
      host_ip: 192.168.84.252
      advertise_ip: 192.168.84.252
      listen_port: 8060

mqtt:
  discovery: true
  broker: 192.168.84.252  # Remove if you want to use builtin-in MQTT broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

webhook:

zigbee2mqtt_networkmap:

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

sensor:
  - platform: dsmr
    port: /dev/ttyUSBp1
    dsmr_version: 5

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: swap_use_percent

media_player:
  - platform: kodi
    host: 192.168.84.7 
    port: 14864
    name: Kodi
    username: !secret kodi_user
    password: !secret kodi_pass 

  - platform: androidtv
    host: 192.168.84.7
    name: "NVidia Shield"


zone:
  - name: !secret ctr_zname
    latitude: !secret ctr_zlat
    longitude: !secret ctr_zlong
    radius: 2000
    icon: mdi:factory

volkswagencarnet:
    username: !secret vw_usr
    password: !secret vw_pwd
    spin: !secret vw_spin
    scandinavian_miles: false
    scan_interval:
        minutes: 2
    name:
        !secret vw_vin: 'Passat'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
