input_boolean:
  alarm_bij_afwezig:
    name: Alarm bij afwezig
    initial: on
    icon: mdi:alarm-light
  alarm_altijd:
    name: Alarm altijd
    initial: off
    icon: mdi:alarm-light
  flash_loop:
    initial: off
    icon: mdi:alarm-light

group:
  alarm_persons:
    entities:
      - person.jasper
      - person.marielle
      - person.marieke
  alarm_lights:
    entities:
      - light.achter_tv
      - light.naast_tv
      - light.salontafel
      - light.gang_lamp

automation:
  - alias: Alarm altijd inschakelen
    trigger:
    - platform: state
      entity_id: sensor.alarm_knop_boven
      to: 'on'
    action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alarm_altijd

  - alias: Alarm altijd uitschakelen
    trigger:
    - platform: state
      entity_id: sensor.alarm_knop_boven
      to: 'off'
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alarm_altijd
    - service: script.turn_on
      entity_id: script.flash_stop

  - alias: Alarm bij automation script
    description: ''
    trigger:
    - entity_id: binary_sensor.gang_sensor_occupancy
      platform: state
      to: 'on'
    - entity_id: binary_sensor.woonkamer_sensor_occupancy
      platform: state
      to: 'on'
    - entity_id: binary_sensor.openslaande_deuren
      platform: state
      to: 'on'
    - entity_id: binary_sensor.voordeur
      platform: state
      to: 'on'
    - entity_id: binary_sensor.frans_balkon
      platform: state
      to: 'on' 
    condition:
      condition: or
      conditions:
        # OF (BIJ AFWEZIG & NIEMAND AANWEZIG)
        - condition: and
          conditions:
            - condition: state
              entity_id: input_boolean.alarm_bij_afwezig
              state: 'on'
            - condition: state
              entity_id: group.alarm_persons
              state: not_home
        # OF SIMPELWEG ALTIJD INGESCHAKELD  
        - condition: state
          entity_id: input_boolean.alarm_altijd
          state: 'on'
    action:
    - service: notify.notify
      data:
        message: "Beweging in huis {{ now().strftime('%H:%M:%S (%Y-%m-%d)') }}"
        title: Alarm
    - service: script.turn_on
      entity_id: script.flash_start
    - service: media_player.volume_set
      data:
        entity_id: media_player.mini
        volume_level: 1
    - service: tts.google_translate_say
      entity_id: media_player.mini
      data:
        message: 'alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!'
    - service: switch.turn_on
      entity_id: switch.osram_smart_plug_switch

  - alias: Flash loop auto-off
    description: ''
    trigger:
    - entity_id: input_boolean.flash_loop
      platform: state
      to: 'on'
    condition: []
    action:
    - timeout: 00:05:00
      wait_template: ''
    - entity_id: input_boolean.flash_loop
      service: input_boolean.turn_off

script:
  flash_start:
    alias: Start alarmlicht
    sequence:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.flash_loop
    - service: script.turn_on
      entity_id: script.flash_cycle

  flash_stop:
    alias: Stop alarmlicht
    sequence:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.flash_loop

  flash_cycle:
    sequence:
    - service: light.turn_on
      data:
        entity_id: 
        - group.alarm_lights
        brightness_pct: 100
        rgb_color: [255,0,0]
        transition: 0
    - delay: 00:00:01
    - service: light.turn_off
      data:
        entity_id:
        - group.alarm_lights
        transition: 0
    - service: script.turn_on
      entity_id: script.flash_loop

  flash_loop:
    sequence:
    - delay: 00:00:02
    - condition: state
      entity_id: input_boolean.flash_loop
      state: 'on'
    - alias: flash_loop
      entity_id: script.flash_cycle
      service: script.turn_on

