input_boolean:

  # Alleen alarm trigger als er niemand thuis is
  alarm_bij_afwezig:
    name: Alarm bij afwezig
    initial: on
    icon: mdi:alarm-light

  # Altijd alarm trigger, ongeacht wie thuis is
  alarm_altijd:
    name: Alarm altijd
    initial: off
    icon: mdi:alarm-light

  # Staat het alarm knipperlicht aan of uit
  alarm_flashing:
    name: Alarm af laten gaan
    initial: off
    icon: mdi:alarm-light


automation:

  # Ikea knop trigger - alarm aan
  - alias: Alarm altijd inschakelen
    mode: restart
    trigger:
    - platform: state
      entity_id: sensor.alarm_knop_boven
      to: 'on'
    action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alarm_altijd
    - service: light.turn_off
      data:
        entity_id:
        - group.alarm_lights

  # Ikea knop trigger - alarm uit
  - alias: Alarm altijd uitschakelen
    mode: queued
    trigger:
    - platform: state
      entity_id: sensor.alarm_knop_boven
      to: 'off'
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alarm_altijd
    - service: input_boolean.turn_off
      entity_id: input_boolean.alarm_flashing

  # Alarm sensor trigger
  - alias: Alarm sensor triggered automation
    description: ''
    mode: single
    trigger:
    - entity_id: binary_sensor.gang_sensor_occupancy
      platform: state
      to: 'on'
    - entity_id: binary_sensor.woonkamer_sensor_occupancy
      platform: state
      to: 'on'
    - entity_id: binary_sensor.openslaande_deuren
      platform: state
      to: 'on'
    - entity_id: binary_sensor.voordeur
      platform: state
      to: 'on'
    - entity_id: binary_sensor.frans_balkon
      platform: state
      to: 'on' 
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_flashing
          state: 'off'
        - condition: or
          conditions:
            # OF (BIJ AFWEZIG & NIEMAND AANWEZIG)
            - condition: and
              conditions:
                - condition: state
                  entity_id: input_boolean.alarm_bij_afwezig
                  state: 'on'
                - condition: state
                  entity_id: group.alarm_persons
                  state: not_home
            # OF SIMPELWEG ALTIJD INGESCHAKELD  
            - condition: state
              entity_id: input_boolean.alarm_altijd
              state: 'on'
    action:
    - service: switch.turn_on
      entity_id: switch.osram_smart_plug_switch

    - service: input_boolean.turn_on
      entity_id: input_boolean.alarm_flashing

    - service: media_player.volume_set
      data:
        entity_id: media_player.mini
        volume_level: 1

    - service: tts.google_translate_say
      entity_id: media_player.mini
      data:
        message: 'alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!, alarm!'

    - service: notify.notify
      data:
        title: Alarm
      data_template:
        message: >
          Beweging in huis {{ now().strftime('%H:%M:%S (%m-%d)') }}, 
          {%- for entity_id in states.group.alarm_persons.attributes.entity_id -%}
            {%- if is_state(entity_id, "home") -%} 
              {%- if not loop.first %}, {% endif -%}
              {{ state_attr(entity_id, "friendly_name") }} is thuis 
            {%- endif -%} 
          {%- endfor %}

  # Alarm auto-uit als getriggerd en daarna iemand uit alarm groep thuiskomt (als wifi verbinding later gemaakt wordt)
  - alias: Flash loop smart-off
    mode: restart
    trigger:
    - platform: state
      entity_id: group.alarm_persons
      to: home
    condition:
    - condition: state
      entity_id: input_boolean.alarm_flashing
      state: 'on'
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alarm_flashing

    - service: notify.notify
      data:
        title: Alarm
      data_template:
        message: >
          {%- for entity_id in states.group.alarm_persons.attributes.entity_id -%}
            {%- if is_state(entity_id, "home") -%}
              {%- if not loop.first %}, {% endif -%}
              {{ state_attr(entity_id, "friendly_name") }} is nu thuis
            {%- endif -%}
          {%- endfor %}



  # Volume van google mini terug naar 40% bij uitschakelen knipperlicht
  - alias: Reset google home volume bij uitschakelen alarmlicht
    mode: restart
    trigger:
    - platform: state
      entity_id: input_boolean.alarm_flashing
      to: 'off'
    action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.mini
        volume_level: .4

  # Alarm script starten bij bool flip
  - alias: Flash loop start and auto-off
    mode: restart
    trigger:
    - entity_id: input_boolean.alarm_flashing
      platform: state
      to: 'on'
    action:
    - service: script.turn_on
      entity_id: script.flash_alarm

script:
  flash_alarm_group:
    mode: restart
    sequence:
      - service: light.turn_on
        data:
          brightness_pct: 100
          rgb_color: [255,0,0]
          transition: 0
        data_template:
          entity_id: "group.{{ group }}"
      - repeat:
          count: "{{ count|int * 2 - 1 }}"
          sequence:
            - condition: state
              entity_id: input_boolean.alarm_flashing
              state: 'on'
            - delay: 00:00:05
            - service: light.turn_on
              data:
                transition: 0
              data_template:
                entity_id: "group.{{ group }}"
            - delay: 00:00:05
            - service: light.turn_off
              data:
                transition: 0
              data_template:
                entity_id: "group.{{ group }}"
      - service: input_boolean.turn_off
        entity_id: input_boolean.alarm_flashing


  flash_alarm:
    sequence:
      - service: script.flash_alarm_group
        data:
          group: alarm_lights
          count: 10

