input_boolean:
  auto_light_iedereen_afwezig:
    name: 'Iedereen meer dan 20min afwezig'
    initial: off
    icon: mdi:hail

  auto_light_buitenlamp_altijd_aan:
    name: 'Buitenlamp dimstand als het donker is'
    initial: on
    icon: mdi:av-timer

automation:
  - alias: '20min afw: Bij vertrek, timer starten om 20min afwezig te bepalen'
    trigger:
      - platform: state
        entity_id: group.auto_light_persons
        from: 'home'
    action:
      - service: script.turn_off
        entity_id: script.set_iedereen_afwezig_na_delay
      - service: script.turn_on
        entity_id: script.set_iedereen_afwezig_na_delay

  - alias: '20min afw: Bij thuiskomst, timer stoppen om 20min afwezig te bepalen'
    trigger:
      - platform: state
        entity_id: group.auto_light_persons
        to: 'home'
    action:
      - service: script.turn_off
        entity_id: script.set_iedereen_afwezig_na_delay

  - alias: '20min afw: Lampen aan bij deur open en iedereen afwezig'
    trigger:
      - entity_id: binary_sensor.openslaande_deuren
        platform: state
        to: 'on'
      - entity_id: binary_sensor.voordeur
        platform: state
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.auto_light_iedereen_afwezig
          state: 'on'
        - condition: time
          after: '16:00:00'
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ state_attr('sun.sun', 'elevation') < 3 }}"
            - condition: template
              value_template: "{{ state_attr('sensor.woonkamer_sensor_illuminance','illuminance_lux') < 8 }}"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.auto_light_iedereen_afwezig
      - service: scene.turn_on
        entity_id: scene.relax_licht
      - service: script.turn_on
        entity_id: script.gang_lamp_script

  - alias: '20 min afw: Iedereen afwezig uitschakelen na 1sec'
    trigger:
    - entity_id: binary_sensor.gang_sensor_occupancy
      platform: state
      to: 'on'
    - entity_id: binary_sensor.woonkamer_sensor_occupancy
      platform: state
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.auto_light_iedereen_afwezig
      state: 'on'
    action:
    - delay: 00:00:01
    - entity_id: input_boolean.auto_light_iedereen_afwezig
      service: input_boolean.turn_off

  - alias: 'Gang lamp automatisch aanzetten'
    description: 'Zet lamp automatisch aan bij beweging, en na 1min weer uit. Reset 1min timer bij beweging binnen 1min'
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.gang_sensor_occupancy
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.gang_lamp_script

  - alias: 'Buitenlamp automatisch fel zetten bij deur open en thuiskomst'
    description: 'Zet lamp automatisch fel zetten bij achterdeur open of thuiskomst, en na 15min weer naar default.'
    mode: restart
    trigger:
      - entity_id: binary_sensor.openslaande_deuren
        platform: state
        to: 'on'
      - platform: zone
        event: enter
        zone: zone.home
        entity_id: device_tracker.pixel_4a
      - platform: zone
        event: enter
        zone: zone.home
        entity_id: device_tracker.pixel_3a
      - platform: zone
        event: enter
        zone: zone.home
        entity_id: device_tracker.passat
    action:
      - service: script.turn_on
        entity_id: script.buitenlamp_achtertuin_fel_script

  - alias: 'Buitenlamp automatisch aan en uit toepassen, bij zonnestand, instelling trigger'
    trigger:
      - platform: state
        entity_id: input_boolean.auto_light_buitenlamp_altijd_aan
        to: 'off'
      - platform: state
        entity_id: input_boolean.auto_light_buitenlamp_altijd_aan
        to: 'on'
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 0
    action:
      - service: script.turn_on
        entity_id: script.buitenlamp_achtertuin_naar_default

  - alias: 'Buitenlamp uitzetten om 02:00 snachts'
    trigger:
      - platform: time
        at: '02:00:00'
    action:
      - service: script.turn_on
        entity_id: script.buitenlamp_achtertuin_uitzetten

script:
  gang_lamp_script:
    mode: restart
    sequence:
      - service: light.turn_on
        entity_id: light.gang_lamp
        data:
          brightness: 255
      - delay: 00:01:00
      - service: light.turn_off
        entity_id: light.gang_lamp

  buitenlamp_achtertuin_fel_script:
    mode: parallel
    sequence:
      # EN
      - condition: and
        conditions:

          # Zon onder de horizon
          - condition: template
            value_template: "{{ state_attr('sun.sun', 'elevation') < 0 }}"

          # OF
          - condition: or
            conditions:

              # Buitenlamp aan EN timer loopt (dan willen we timer resetten) EN lamp staat op dimstand
              - condition: and
                conditions:
                  - condition: state
                    entity_id: 'light.buitenlamp_achtertuin_light'
                    state: 'on'
                  - condition: state
                    entity_id: 'script.buitenlamp_achtertuin_timer'
                    state: 'on'
                  - condition: template
                    value_template: "{{ state_attr('light.buitenlamp_achtertuin_light', 'brightness') == 120 }}"

              # Buitenlamp uit (dan willen we timer starten)
              - condition: state
                entity_id: 'light.buitenlamp_achtertuin_light'
                state: 'off'
 
      - service: script.turn_on
        entity_id: script.buitenlamp_achtertuin_timer

  buitenlamp_achtertuin_timer:
    mode: restart
    sequence:
      - service: light.turn_on
        entity_id: light.buitenlamp_achtertuin_light
        data:
          brightness: 255
          effect: none
          transition: 1
          rgb_color:
          - 255
          - 197
          - 101
      - delay: 00:15:00
      - service: script.turn_on
        entity_id: script.buitenlamp_achtertuin_naar_default

  buitenlamp_achtertuin_naar_default:
    mode: restart
    sequence:
      - service_template: >
          {% if(state_attr('sun.sun', 'elevation') < 0) and is_state('input_boolean.auto_light_buitenlamp_altijd_aan', 'on')  %} script.buitenlamp_achtertuin_naar_dimstand
          {% else %}  script.buitenlamp_achtertuin_uitzetten {% endif %} 

  buitenlamp_achtertuin_naar_dimstand:
    mode: restart
    sequence:
      - condition: state
        entity_id: input_boolean.auto_light_buitenlamp_altijd_aan
        state: 'on'
      - service: light.turn_on
        entity_id: light.buitenlamp_achtertuin_light
        data:
          brightness: 120
          effect: none
          transition: 1
          rgb_color:
          - 255
          - 197
          - 101

  buitenlamp_achtertuin_uitzetten:
    mode: restart
    sequence:
      - service: light.turn_off
        entity_id: light.buitenlamp_achtertuin_light

  set_iedereen_afwezig_na_delay:
    sequence:
      - delay: 00:20:00
      - service: input_boolean.turn_on
        entity_id: input_boolean.auto_light_iedereen_afwezig


  
