input_boolean:
  auto_light_iedereen_afwezig:
    name: Iedereen meer dan 20min afwezig
    initial: off
    icon: mdi:hail

automation:
  - alias: 'Iedereen afwezig instellen na timer'
    trigger:
      - platform: state
        entity_id: group.auto_light_persons
        from: 'home'
    action:
      - service: script.turn_off
        entity_id: script.set_iedereen_afwezig_na_delay
      - service: script.turn_on
        entity_id: script.set_iedereen_afwezig_na_delay

  - alias: 'Iedereen afwezig timer uitschakelen bij aanwezig'
    trigger:
      - platform: state
        entity_id: group.auto_light_persons
        to: 'home'
    action:
      - service: script.turn_off
        entity_id: script.set_iedereen_afwezig_na_delay

  - alias: 'Lampen aan bij deur open en iedereen afwezig'
    trigger:
      - entity_id: binary_sensor.openslaande_deuren
        platform: state
        to: 'on'
      - entity_id: binary_sensor.voordeur
        platform: state
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.auto_light_iedereen_afwezig
          state: 'on'
        - condition: time
          after: '16:00:00'
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ state_attr('sun.sun', 'elevation') < 3 }}"
            - condition: template
              value_template: "{{ state_attr('sensor.woonkamer_sensor_illuminance','illuminance_lux') < 8 }}"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.auto_light_iedereen_afwezig
      - service: scene.turn_on
        entity_id: scene.relax_licht
      - service: script.turn_on
        entity_id: script.gang_lamp_script

  - alias: Gang lamp automatisch aanzetten
    description: 'Zet lamp automatisch aan bij beweging, en na 1min weer uit. Reset 1min timer bij beweging binnen 1min'
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.gang_sensor_occupancy
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.gang_lamp_script

  - alias: Buitenlamp automatisch aanzetten
    description: 'Zet lamp automatisch aan bij achterdeur open of thuiskomst, en na 15min weer uit.'
    mode: restart
    trigger:
      - entity_id: binary_sensor.openslaande_deuren
        platform: state
        to: 'on'
      - platform: zone
        event: enter
        zone: zone.home
        entity_id: device_tracker.pixel_4a
      - platform: zone
        event: enter
        zone: zone.home
        entity_id: device_tracker.pixel_3a
    action:
      - service: script.turn_on
        entity_id: script.buitenlamp_achtertuin_script

  - alias: Iedereen afwezig uitschakelen na 1sec
    trigger:
    - entity_id: binary_sensor.gang_sensor_occupancy
      platform: state
      to: 'on'
    - entity_id: binary_sensor.woonkamer_sensor_occupancy
      platform: state
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.auto_light_iedereen_afwezig
      state: 'on'
    action:
    - delay: 00:00:01
    - entity_id: input_boolean.auto_light_iedereen_afwezig
      service: input_boolean.turn_off


script:
  gang_lamp_script:
    mode: restart
    sequence:
      - service: light.turn_on
        entity_id: light.gang_lamp
        data:
          brightness: 255
      - delay: 00:01:00
      - service: light.turn_off
        entity_id: light.gang_lamp

  buitenlamp_achtertuin_script:
    mode: parallel
    sequence:
      # EN
      - condition: and
        conditions:

          # Zon onder de horizon
          - condition: template
            value_template: "{{ state_attr('sun.sun', 'elevation') < 0 }}"

          # OF
          - condition: or
            conditions:

              # Buitenlamp aan EN timer loopt (dan willen we timer resetten)
              - condition: and
                conditions:
                  - condition: state
                    entity_id: 'light.buitenlamp_achtertuin_light'
                    state: 'on'
                  - condition: state
                    entity_id: 'script.buitenlamp_achtertuin_timer'
                    state: 'on'

              # Buitenlamp uit (dan willen we timer starten)
              - condition: state
                entity_id: 'light.buitenlamp_achtertuin_light'
                state: 'off'
 
      - service: script.turn_on
        entity_id: script.buitenlamp_achtertuin_timer

  buitenlamp_achtertuin_timer:
    mode: restart
    sequence:
      - service: light.turn_on
        entity_id: light.buitenlamp_achtertuin_light
        data:
          brightness: 255
      - delay: 00:15:00
      - service: light.turn_off
        entity_id: light.buitenlamp_achtertuin_light

  set_iedereen_afwezig_na_delay:
    sequence:
      - delay: 00:20:00
      - service: input_boolean.turn_on
        entity_id: input_boolean.auto_light_iedereen_afwezig


  
