sensor:
  - platform: template
    sensors:
      studeerzolder_temperature:
        friendly_name: "Studeerzolder temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.thermostaat_studeerzolder_climate', 'current_temperature') }}"
      voordeur_last_opened:
        friendly_name: 'Voordeur laatst geopend'
        entity_id: binary_sensor.voordeur
        icon_template: mdi:glassdoor
        value_template: '{{ as_timestamp(states.binary_sensor["voordeur"].last_updated) | timestamp_custom("%a %m %b %H:%M", True) }}'
      openslaande_deuren_last_opened:
        friendly_name: 'Openslaande deuren laatst geopend'
        entity_id: binary_sensor.openslaande_deuren
        icon_template: mdi:glassdoor
        value_template: '{{ as_timestamp(states.binary_sensor["openslaande_deuren"].last_updated) | timestamp_custom("%a %m %b %H:%M", True) }}'
      frans_balkon_last_opened:
        friendly_name: 'Frans balkon laatst geopend'
        entity_id: binary_sensor.frans_balkon
        icon_template: mdi:glassdoor
        value_template: '{{ as_timestamp(states.binary_sensor["frans_balkon"].last_updated) | timestamp_custom("%a %m %b %H:%M", True) }}'

