# Specifically include sensors to log to improve NAS system performance
recorder:
  db_url: !secret db_url
  purge_keep_days: 10
  include:
    entities:
      # beweging
      - binary_sensor.gang_sensor_occupancy
      - binary_sensor.woonkamer_sensor_occupancy

      # deuren
      - binary_sensor.voordeur
      - binary_sensor.openslaande_deuren
      - binary_sensor.frans_balkon

      # aanwezig
      - person.jasper
      - person.marielle
      - person.marieke
      - person.gerry
    
      # locatie
      - device_tracker.passat
      - device_tracker.pixel_3a
      - device_tracker.pixel_4a

      # wifi
      - device_tracker.unifi_jasper_pixel_4a
      - device_tracker.unifi_marielle_pixel_3a

      # energie
      - sensor.power_consumption
      - sensor.power_production

      # klimaat
      - climate.thermostaat_studeerzolder_climate
      - sensor.studeerzolder_temperature
      - sensor.gang_sensor_temperature
      - sensor.woonkamer_sensor_temperature

sensor:
  - platform: template
    sensors:
      studeerzolder_temperature:
        friendly_name: "Studeerzolder temperatuur"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.thermostaat_studeerzolder_climate', 'current_temperature') }}"


