automation:
  - alias: Volume harder
    trigger:
    - entity_id: sensor.volumeknop_action
      platform: state
      to: 'rotate_right'
    condition:
      - condition: template
        value_template: "{{ state_attr('remote.woonkamer', 'current_activity') != 'off' }}"
    action:
     - service: remote.send_command
       data:
         entity_id: remote.woonkamer
         command: VolumeUp
         num_repeats: 3
         device: 'ONKYO'

  - alias: Volume zachter
    description: ''
    trigger:
    - entity_id: sensor.volumeknop_action
      platform: state
      to: 'rotate_left'
    condition:
      - condition: template
        value_template: "{{ state_attr('remote.woonkamer', 'current_activity') != 'off' }}"
    action:
     - service: remote.send_command
       data:
         entity_id: remote.woonkamer
         command: VolumeDown
         num_repeats: 3
         device: 'ONKYO'

  #
  # For the E1744 symfonisk bind to MQTT event. The device state in home assistant becomes play_pause after buttong press.
  # Problem is it also stays that way. So state trigger won't fire twice. Solution is to bind to MQTT event instead.
  #
  - alias: Pause
    description: ''
    trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/volumeknop/action'
    condition:
      - condition: template
        value_template: '{{ "play_pause" == trigger.payload }}'
      - condition: template
        value_template: "{{ state_attr('remote.woonkamer', 'current_activity') != 'off' }}"
    action:
      - service: remote.send_command
        data:
          entity_id: remote.woonkamer
          command: Pause
          device: 'HTPC'
